services:
  db:
    image: postgres:16-alpine
    container_name: skeleton-db-dev
    environment:
      POSTGRES_USER: skeleton
      POSTGRES_PASSWORD: skeleton
      POSTGRES_DB: skeleton_db
    ports:
      - "5433:5432"
    volumes:
      - skeleton_db_data:/var/lib/postgresql/data

volumes:
  skeleton_db_data:
    driver: local